# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format="(orange)[$directory](orange)$character"
right_format = "$all"

palette="my"

[palettes.my]
mustard = "#af8700"
prompt = "#ffa600"
character = "#007ACC"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](character)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
style="prompt"
# format="[$path]($style)[$read_only]($read_only_style) "	

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = true